---
title: "Projects"
output: html_document
  
---
Below is a sample of some projects and mini-projects I've completed. Most of them have a data science focus. I have more project samples on my Github profile, including a [naive bayes classifier](https://github.com/JulianneZech/naivebayes), a [neural network](https://github.com/JulianneZech/neuralnetwork), and an [association rule mining engine](https://github.com/JulianneZech/associationmining) that I built as a part of my data mining class in the spring of 2019. I also have assorted projects from my Big Data Analytics course available, including [word counts](https://github.com/JulianneZech/Wikipedia-Word-Counts), [sports article classification](https://github.com/JulianneZech/Sports-Classification), and a simplified implementation of [PageRank](https://github.com/JulianneZech/Wikipedia-PageRank) on the entire ~70 GB English Wikipedia corpus using  Spark's Scala API. 



I am currently implementing a machine learning model in Python that I have entered in the FinTech competition track at [Hack GCL](https://www.girlscomputingleague.org/events/hack-gcl-at-capital-one/), a national hackathon for students. I will publish Jupyter notebooks with code, visualizations, explanations, and results here when the project is completed in September. 


I also enjoy competing in Kaggle competitions and I'm hoping to publish some of my strategies and code samples here soon.


---


## [Correlations between Poverty & Health Insurance](https://juliannezech.shinyapps.io/lab2/)


---


## [Analyzing Food Preferences of Americans](projects/MyWork_FullLab01.html)


---


## [Graphing Heroin Usage and Annual Income](projects/my_work_-_MiniLab01_-_Initial_Work.html)


---


## [Exploring Police Shootings in the United States](projects/my-work-police-shooting-graphs.html)


---
